In [1]:
# Data Processing
import pandas as pd
import numpy as np

In [3]:
# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

In [5]:
# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz

In [6]:
cars = pd.read_csv('data/car.csv')

In [8]:
cars.shape

(1728, 7)

In [9]:
cars.head()

   price maintenance doors seats storage safety shouldBuy
0  vhigh       vhigh     2     2   small    low     unacc
1  vhigh       vhigh     2     2   small    med     unacc
2  vhigh       vhigh     2     2   small   high     unacc
3  vhigh       vhigh     2     2     med    low     unacc
4  vhigh       vhigh     2     2     med    med     unacc

In [10]:
cars.describe()

        price maintenance doors seats storage safety shouldBuy
count    1728        1728  1728  1728    1728   1728      1728
unique      4           4     4     3       3      3         4
top     vhigh       vhigh     2     2   small    low     unacc
freq      432         432   432   576     576    576      1210

In [11]:
cars.isnull().sum()

price          0
maintenance    0
doors          0
seats          0
storage        0
safety         0
shouldBuy      0
dtype: int64